image: docker:git

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  TMPDIR: "${CI_PROJECT_DIR}.tmp"
  CACHE_DIR: ${CI_PROJECT_DIR}/ccache

cache:
  key: "${CI_JOB_NAME}" # https://docs.gitlab.com/ee/ci/caching/#sharing-caches-across-different-branches
  paths:
    - ccache

services:
  - docker:19.03.5-dind

noetic:
  before_script:
    - apk add --update bash coreutils tar
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
  script: .industrial_ci/gitlab.sh DOCKER_RUN_OPTS="-v /etc/ssl/certs:/etc/ssl/certs:ro"
  variables:
    ROS_DISTRO: noetic
    DOCKER_IMAGE: "ros:noetic-robot"

linting:
  image: python:3.9
  before_script:
    - python3 -m pip install black==22.8 isort==5.10.1 flake8==5.0.4
  script:
    - black -l 129 --check --diff --color .
    - isort -l 120 --check-only --profile black .
    - flake8 --max-line-length 120 --per-file-ignores="__init__.py:F401,F403" .
  allow_failure: true
