name: composite_repair_dashboard
dependencies:
  - python=3.9
  - pip
  - pip:
      - black
      - numpy
      - flask
      - dash
      - pandas
      - plotly
      - open3d
      - gunicorn
      - pdf2image
